package com.exelynt.booking;

import com.exelynt.booking.entity.*; import com.exelynt.booking.repository.*; import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import java.math.BigDecimal; import java.time.LocalDateTime; import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") class BookingApiIntegrationTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired UserRepository users; @Autowired ResourceRepository resources; @Autowired ReservationRepository reservations; @Autowired PasswordEncoder encoder;
 String admin,userA,userB; Resource room;
 @BeforeEach void setup() throws Exception { reservations.deleteAll(); resources.deleteAll(); users.deleteAll(); addUser("admin",Role.ADMIN); addUser("userA",Role.USER); addUser("userB",Role.USER); room=resource("Room A",new BigDecimal("100.00")); admin=token("admin","pass");userA=token("userA","pass");userB=token("userB","pass"); }
 void addUser(String name,Role role){User u=new User();u.setUsername(name);u.setEmail(name+"@test.local");u.setPassword(encoder.encode("pass"));u.setRole(role);users.save(u);} Resource resource(String n,BigDecimal p){Resource r=new Resource();r.setName(n);r.setDescription("test");r.setType("ROOM");r.setLocation("HQ");r.setPrice(p);r.setAvailable(true);return resources.save(r);} String token(String username,String pass)throws Exception{String body=mvc.perform(post("/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+username+"\",\"password\":\""+pass+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(body).get("token").asText();} String auth(String t){return "Bearer "+t;} String request(long id,LocalDateTime start,LocalDateTime end,String status){return "{\"resourceId\":"+id+",\"startTime\":\""+start+"\",\"endTime\":\""+end+"\",\"status\":\""+status+"\"}";} long create(String token,Resource r,LocalDateTime s,LocalDateTime e,String state)throws Exception{String response=mvc.perform(post("/api/reservations").header("Authorization",auth(token)).contentType(MediaType.APPLICATION_JSON).content(request(r.getId(),s,e,state))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(response).get("id").asLong();}
 @Test void loginJwtAndUnauthenticatedAccess() throws Exception {assertThat(token("admin","pass")).isNotBlank(); mvc.perform(get("/api/resources")).andExpect(status().isUnauthorized()); assertThatThrownBy(()->token("admin","wrong")).isInstanceOf(AssertionError.class);}
 @Test void resourceRbacIsEnforced() throws Exception {String body="{\"name\":\"x\",\"type\":\"R\",\"location\":\"H\",\"price\":1,\"available\":true}";mvc.perform(get("/api/resources").header("Authorization",auth(userA))).andExpect(status().isOk());mvc.perform(get("/api/resources/"+room.getId()).header("Authorization",auth(userA))).andExpect(status().isOk());mvc.perform(get("/api/resources")).andExpect(status().isUnauthorized()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON)).andExpect(jsonPath("$.status").value(401));mvc.perform(get("/api/resources").header("Authorization","Bearer bad.token.value")).andExpect(status().isUnauthorized()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON)).andExpect(jsonPath("$.message").value("Invalid or expired JWT"));mvc.perform(post("/api/resources").header("Authorization",auth(userA)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON)).andExpect(jsonPath("$.status").value(403));mvc.perform(put("/api/resources/"+room.getId()).header("Authorization",auth(userA)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());mvc.perform(delete("/api/resources/"+room.getId()).header("Authorization",auth(userA))).andExpect(status().isForbidden());mvc.perform(post("/api/resources").header("Authorization",auth(admin)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated());}
 @Test void principalDeterminesOwnershipAndUsersCannotReadOthers() throws Exception {LocalDateTime t=LocalDateTime.now().plusDays(1).withNano(0);long id=create(userA,room,t,t.plusHours(2),"PENDING");Reservation r=reservations.findById(id).orElseThrow();assertThat(r.getUser().getId()).isEqualTo(users.findByUsername("userA").orElseThrow().getId());mvc.perform(get("/api/reservations/"+id).header("Authorization",auth(userA))).andExpect(status().isOk());mvc.perform(get("/api/reservations/"+id).header("Authorization",auth(userB))).andExpect(status().isForbidden());mvc.perform(get("/api/reservations/"+id).header("Authorization",auth(admin))).andExpect(status().isOk());mvc.perform(get("/api/reservations").header("Authorization",auth(userB))).andExpect(jsonPath("$.totalElements").value(0));}
 @Test void maliciousUserIdCannotImpersonate() throws Exception {LocalDateTime t=LocalDateTime.now().plusDays(1).withNano(0);Long b=users.findByUsername("userB").orElseThrow().getId();String payload=request(room.getId(),t,t.plusHours(1),"PENDING").replace("{","{\"userId\":"+b+",");String body=mvc.perform(post("/api/reservations").header("Authorization",auth(userA)).contentType(MediaType.APPLICATION_JSON).content(payload)).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long id=json.readTree(body).get("id").asLong();assertThat(reservations.findById(id).orElseThrow().getUser().getId()).isEqualTo(users.findByUsername("userA").orElseThrow().getId());}
 @Test void validationAndNotFoundResponses() throws Exception {mvc.perform(post("/api/reservations").header("Authorization",auth(userA)).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isBadRequest());mvc.perform(get("/api/resources/999999").header("Authorization",auth(userA))).andExpect(status().isNotFound());mvc.perform(get("/api/reservations/999999").header("Authorization",auth(admin))).andExpect(status().isNotFound());}
 @Test void conflictAdjacentCancelledAndDifferentResourceBehavior() throws Exception {LocalDateTime t=LocalDateTime.now().plusDays(1).withNano(0);create(userA,room,t,t.plusHours(2),"CONFIRMED");mvc.perform(post("/api/reservations").header("Authorization",auth(userB)).contentType(MediaType.APPLICATION_JSON).content(request(room.getId(),t.plusHours(1),t.plusHours(3),"PENDING"))).andExpect(status().isConflict());create(userB,room,t.plusHours(2),t.plusHours(4),"PENDING");Resource other=resource("Room B",new BigDecimal("250"));create(userB,other,t.plusHours(1),t.plusHours(3),"CANCELLED");create(userA,other,t.plusHours(1),t.plusHours(3),"PENDING");}
 @Test void adminFilteringPaginationSortingAndCrud() throws Exception {LocalDateTime t=LocalDateTime.now().plusDays(1).withNano(0);Resource expensive=resource("Premium",new BigDecimal("500"));create(userA,room,t,t.plusHours(1),"PENDING");create(userB,expensive,t.plusHours(2),t.plusHours(3),"CONFIRMED");mvc.perform(get("/api/reservations?minPrice=100&maxPrice=500&sort=price,desc&page=0&size=1").header("Authorization",auth(admin))).andExpect(status().isOk()).andExpect(jsonPath("$.content.length()").value(1)).andExpect(jsonPath("$.totalElements").value(2)).andExpect(jsonPath("$.content[0].price").value(500));mvc.perform(get("/api/reservations?sort=unknown,asc").header("Authorization",auth(admin))).andExpect(status().isBadRequest());}
}
